# Captured from the current laptop on 2026-09-17.
# Curate this list as tools and applications fall out of use.

tap "argoproj/tap"
tap "derailed/k9s"
tap "getagentseal/codeburn"
tap "hashicorp/tap"
tap "madappgang/tap"
tap "node9-ai/node9"

# Shell and development tools
brew "actionlint"
brew "ansible"
brew "argocd"
brew "asdf"
brew "aws-sam-cli"
brew "bash"
brew "blueutil"
brew "btop"
brew "cmake"
brew "docker-credential-helper-ecr"
brew "duti"
brew "dyff"
brew "eksctl"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "getagentseal/codeburn/codeburn"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "glab"
brew "go"
brew "gomplate"
brew "graphviz"
brew "helm"
brew "kind"
brew "derailed/k9s/k9s"
brew "kubent"
brew "kustomize"
brew "latexindent"
brew "lazygit"
brew "libpq"
brew "libvterm"
brew "msgpack"
brew "mvnvm"
brew "neovim"
brew "opentofu"
brew "openvpn"
brew "pinentry-mac"
brew "pipx"
brew "poppler"
brew "pre-commit"
brew "python-tk@3.10"
brew "python@3.12"
brew "ripgrep"
brew "rtk"
brew "ruby@3.4"
brew "rust"
brew "skopeo"
brew "sops"
brew "tcl-tk"
brew "terminal-notifier"
brew "hashicorp/tap/terraform"
brew "tfenv"
brew "thefuck"
brew "tmux"
brew "tree"
brew "watch"
brew "yamlfmt"
brew "yamllint"
brew "yq"

# Applications currently managed by Homebrew
cask "1password-cli"
cask "drawio"
cask "hammerspoon"

# Additional applications managed through Homebrew casks
cask "1password"
cask "adguard"
cask "arc"
cask "betterdisplay"
cask "claude"
cask "cursor"
cask "docker-desktop"
cask "intellij-idea"
cask "iterm2"
cask "lookaway"
cask "notion"
cask "obsidian"
cask "raycast"
cask "setapp"
cask "slack"
cask "spotify"
cask "stremio"

# User-installed font families
cask "font-hack-nerd-font"
cask "font-monaspace"
