#!/usr/bin/env node

// Decodes sprites/<mon>/*.gif with ffmpeg and writes hooks/frames.js.
// Each frame becomes rows of palette letters plus its duration, cropped per mon
// to the box every one of its frames fits in.
// Add a mon by dropping its four GIFs from jakobhoeg/vscode-pokemon into sprites/<mon>/.
// Run from anywhere: node scripts/build-frames.mjs

import { execFileSync } from 'node:child_process'
import { readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SIZE = 32
const VARIANTS = ['default', 'shiny']
const ANIMS = ['idle', 'walk']
const LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

function decode(file) {
  const raw = execFileSync('ffmpeg', [
    '-v', 'error', '-i', file, '-fps_mode', 'passthrough',
    '-f', 'rawvideo', '-pix_fmt', 'rgba', '-',
  ])
  const durations = execFileSync('ffprobe', [
    '-v', 'error', '-show_entries', 'frame=duration_time', '-of', 'csv=p=0', file,
  ]).toString().trim().split('\n').map((s) => Math.round(Number(s) * 1000) || 100)

  const frameBytes = SIZE * SIZE * 4
  const frames = []
  for (let off = 0, k = 0; off < raw.length; off += frameBytes, k++) {
    const px = []
    for (let i = 0; i < SIZE * SIZE; i++) {
      const p = off + i * 4
      px.push(raw[p + 3] > 127 ? (raw[p] << 16) | (raw[p + 1] << 8) | raw[p + 2] : null)
    }
    frames.push({ ms: durations[k] ?? 100, px })
  }
  return frames
}

function buildMon(mon) {
  const sheets = {}
  for (const v of VARIANTS) {
    sheets[v] = {}
    for (const a of ANIMS) sheets[v][a] = decode(join(ROOT, 'sprites', mon, `${v}_${a}_8fps.gif`))
  }

  let minX = SIZE, minY = SIZE, maxX = -1, maxY = -1
  for (const v of VARIANTS) for (const a of ANIMS) for (const { px } of sheets[v][a]) {
    px.forEach((c, i) => {
      if (c === null) return
      const x = i % SIZE, y = Math.floor(i / SIZE)
      minX = Math.min(minX, x); maxX = Math.max(maxX, x)
      minY = Math.min(minY, y); maxY = Math.max(maxY, y)
    })
  }

  const out = { width: maxX - minX + 1, height: maxY - minY + 1, variants: {} }
  for (const v of VARIANTS) {
    const palette = []
    const letter = (c) => {
      if (c === null) return '.'
      let i = palette.indexOf(c)
      if (i < 0) i = palette.push(c) - 1
      return LETTERS[i]
    }
    const anims = {}
    for (const a of ANIMS) {
      anims[a] = sheets[v][a].map(({ ms, px }) => {
        const rows = []
        for (let y = minY; y <= maxY; y++) {
          let row = ''
          for (let x = minX; x <= maxX; x++) row += letter(px[y * SIZE + x])
          rows.push(row)
        }
        return { ms, rows }
      })
    }
    out.variants[v] = { palette: palette.map((c) => '#' + c.toString(16).padStart(6, '0')), ...anims }
  }
  return out
}

const mons = readdirSync(join(ROOT, 'sprites'), { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()

const sprites = Object.fromEntries(mons.map((mon) => [mon, buildMon(mon)]))

const body = `// Generated by scripts/build-frames.mjs from sprites/<mon>/*.gif. Do not edit by hand.
// Each frame is its duration and rows of palette letters; '.' is transparent.

export const SPRITES = ${JSON.stringify(sprites, null, 2)}
`
writeFileSync(join(ROOT, 'hooks', 'frames.js'), body)
for (const [mon, s] of Object.entries(sprites)) {
  const counts = ANIMS.map((a) => `${a} ${s.variants.default[a].length}f`).join(', ')
  console.log(`${mon}: ${s.width}x${s.height}px, ${counts}`)
}
