// Generated by scripts/build-frames.mjs from sprites/<mon>/*.gif. Do not edit by hand.
// Each frame is its duration and rows of palette letters; '.' is transparent.

export const SPRITES = {
  "abra": {
    "width": 19,
    "height": 19,
    "variants": {
      "default": {
        "palette": [
          "#000000",
          "#483818",
          "#b89828",
          "#f8d860",
          "#907860",
          "#786038"
        ],
        "idle": [
          {
            "ms": 300,
            "rows": [
              "...................",
              "...................",
              "........aaaaa......",
              "....bbbacdddcabbb..",
              "....bddcdddddcddb..",
              "....bcdddddddddcb..",
              ".....bdddddddddb...",
              "....bcdddddddddcb..",
              "....acbadddddabca..",
              "....acddadddaddca..",
              ".....aadddddddaa...",
              "....beeaadddaaeeb..",
              "....affbcaaacbffa..",
              ".....aaccbfbccaa...",
              "...bbdcaccbccacdbb.",
              "...bdccaddaddaccdb.",
              "....bbccaaaaaccbb..",
              "......aa.....aa....",
              "..................."
            ]
          },
          {
            "ms": 300,
            "rows": [
              "...................",
              "........aaaaa......",
              "....bbbacdddcabbb..",
              "....bddcdddddcddb..",
              "....bcdddddddddcb..",
              ".....bdddddddddb...",
              "....bcdddddddddcb..",
              "....acbadddddabca..",
              "....acddadddaddca..",
              ".....aadddddddaa...",
              "....beeaadddaaeeb..",
              "....affbcaaacbffa..",
              ".....aaccbfbccaa...",
              "...bbdcaccbccacdbb.",
              "...bdccaddaddaccdb.",
              "....bbccaaaaaccbb..",
              "......aa.....aa....",
              "...................",
              "..................."
            ]
          }
        ],
        "walk": [
          {
            "ms": 300,
            "rows": [
              "...................",
              ".........bb........",
              "........bccbba.....",
              "........aabcddba...",
              ".......addcbdddda..",
              ".......accddddddda.",
              "........accddddddb.",
              ".......bcbdddddddda",
              ".......acddddbadddb",
              ".......adddddddaddb",
              ".bb.....accdddddbb.",
              "bcb....afaaaaaaa...",
              "bccbbb.afffab......",
              "bccfccbcaaacbbb....",
              ".bffcccaffbacaaa...",
              "..bbcccabbccacda...",
              "....babbaccccdb....",
              ".........aabccb....",
              "............bb....."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".........bb........",
              "........bccbba.....",
              "........aabcddba...",
              ".......addcbdddda..",
              ".......accddddddda.",
              "........accddddddb.",
              ".......bcbdddddddda",
              "..bb...acddddbadddb",
              ".bcb...adddddddaddb",
              ".bcb....accdddddbb.",
              ".bcfb..afaaaaaaa...",
              ".affcbbafffab......",
              "..bcccccaaacbbb....",
              "..accccaffbacaaa...",
              "...abccabbccacda...",
              ".....abbaccccdb....",
              ".........aabccb....",
              "............bb.....",
              "..................."
            ]
          }
        ]
      },
      "shiny": {
        "palette": [
          "#000000",
          "#604820",
          "#d8b870",
          "#f8e0a0",
          "#a89080",
          "#a08048"
        ],
        "idle": [
          {
            "ms": 300,
            "rows": [
              "...................",
              "...................",
              "........aaaaa......",
              "....bbbacdddcabbb..",
              "....bddcdddddcddb..",
              "....bcdddddddddcb..",
              ".....bdddddddddb...",
              "....bcdddddddddcb..",
              "....acbadddddabca..",
              "....acddadddaddca..",
              ".....aadddddddaa...",
              "....beeaadddaaeeb..",
              "....affbcaaacbffa..",
              ".....aaccbfbccaa...",
              "...bbdcaccbccacdbb.",
              "...bdccaddaddaccdb.",
              "....bbccaaaaaccbb..",
              "......aa.....aa....",
              "..................."
            ]
          },
          {
            "ms": 300,
            "rows": [
              "...................",
              "........aaaaa......",
              "....bbbacdddcabbb..",
              "....bddcdddddcddb..",
              "....bcdddddddddcb..",
              ".....bdddddddddb...",
              "....bcdddddddddcb..",
              "....acbadddddabca..",
              "....acddadddaddca..",
              ".....aadddddddaa...",
              "....beeaadddaaeeb..",
              "....affbcaaacbffa..",
              ".....aaccbfbccaa...",
              "...bbdcaccbccacdbb.",
              "...bdccaddaddaccdb.",
              "....bbccaaaaaccbb..",
              "......aa.....aa....",
              "...................",
              "..................."
            ]
          }
        ],
        "walk": [
          {
            "ms": 300,
            "rows": [
              "...................",
              ".........bb........",
              "........bccbba.....",
              "........aabcddba...",
              ".......addcbdddda..",
              ".......accddddddda.",
              "........accddddddb.",
              ".......bcbdddddddda",
              ".......acddddbadddb",
              ".......adddddddaddb",
              ".bb.....accdddddbb.",
              "bcb....afaaaaaaa...",
              "bccbbb.afffab......",
              "bccfccbcaaacbbb....",
              ".bffcccaffbacaaa...",
              "..bbcccabbccacda...",
              "....babbaccccdb....",
              ".........aabccb....",
              "............bb....."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".........bb........",
              "........bccbba.....",
              "........aabcddba...",
              ".......addcbdddda..",
              ".......accddddddda.",
              "........accddddddb.",
              ".......bcbdddddddda",
              "..bb...acddddbadddb",
              ".bcb...adddddddaddb",
              ".bcb....accdddddbb.",
              ".bcfb..afaaaaaaa...",
              ".affcbbafffab......",
              "..bcccccaaacbbb....",
              "..accccaffbacaaa...",
              "...abccabbccacda...",
              ".....abbaccccdb....",
              ".........aabccb....",
              "............bb.....",
              "..................."
            ]
          }
        ]
      }
    }
  },
  "bulbasaur": {
    "width": 20,
    "height": 17,
    "variants": {
      "default": {
        "palette": [
          "#406030",
          "#60a810",
          "#000000",
          "#88e020",
          "#404040",
          "#68d078",
          "#409850",
          "#e8e8f8",
          "#681018",
          "#c8c8c8",
          "#b83018"
        ],
        "idle": [
          {
            "ms": 100,
            "rows": [
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              "..ecfgeeeeegfcge....",
              ".egcfffffgfffcge....",
              ".egefffggffffea.....",
              ".ecgfffggffffgc.....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..ecggfffffggca.....",
              "..cgccggfggccga.....",
              "...ccacccccaggc.....",
              "............cc......",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              "..ecfgeeeeegfcge....",
              ".egcfffffgfffcge....",
              ".egefffggffffea.....",
              ".ecgfffggffffgc.....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..ecggfffffggca.....",
              "..cgccggfggccga.....",
              "...ccacccccaggc.....",
              "............cc......",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              "..ecfgeeeeegfcge....",
              ".egcfffffgfffcge....",
              ".egefffggffffea.....",
              ".ecgfffggffffgc.....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..ecggfffffggca.....",
              "..cgccggfggccga.....",
              "...ccacccccaggc.....",
              "............cc......",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              ".egcfgeeeeegfce.....",
              ".egcfffffgfffcge....",
              "..aefffggffffege....",
              "..cgfffggffffgce....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..acggfffffggce.....",
              "..agccggfggccgc.....",
              "..cggacccccacc......",
              "...cc..............."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              ".egcfgeeeeegfce.....",
              ".egcfffffgfffcge....",
              "..aefffggffffege....",
              "..cgfffggffffgce....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..acggfffffggce.....",
              "..agccggfggccgc.....",
              "..cggacccccacc......",
              "...cc..............."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              ".egcfgeeeeegfce.....",
              ".egcfffffgfffcge....",
              "..aefffggffffege....",
              "..cgfffggffffgce....",
              "..cghigfffgihgc.....",
              "..cgjkfffffkjgc.....",
              "..acggfffffggce.....",
              "..agccggfggccgc.....",
              "..cggacccccacc......",
              "...cc..............."
            ]
          }
        ],
        "walk": [
          {
            "ms": 100,
            "rows": [
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "....cggfffggaaccc...",
              "...cggggccgggaa.....",
              "...cggccaaacggc.....",
              "....cc......cc......",
              "....................",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "....cggfffggaaccc...",
              "...cggggccgggaa.....",
              "...cggccaaacggc.....",
              "....cc......cc......",
              "....................",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "....cggfffggaaccc...",
              "...cggggccgggaa.....",
              "...cggccaaacggc.....",
              "....cc......cc......",
              "....................",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "...cagggffggaaccc...",
              "...cacggagggcga.....",
              "....ccggccggca......",
              "......cc..cc........",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "...cagggffggaaccc...",
              "...cacggagggcga.....",
              "....ccggccggca......",
              "......cc..cc........",
              "...................."
            ]
          },
          {
            "ms": 100,
            "rows": [
              "....................",
              "......aaaa..........",
              "...ccadddba.aaa.....",
              "..cbbdddbbbccgfaa...",
              "..cbbbbbbecgfffgga..",
              "..abddbbeffffffggfa.",
              ".abbddbbegffffffffa.",
              ".abbbbbbeggffffffgfa",
              ".abbbbbbcgfffffffffa",
              "..abbbbcffgfffhifffa",
              "...ccccfffafffjkgfga",
              "....cgfffffafffffac.",
              "...cagggffggaaccc...",
              "...cacggagggcga.....",
              "....ccggccggca......",
              "......cc..cc........",
              "...................."
            ]
          }
        ]
      },
      "shiny": {
        "palette": [
          "#406030",
          "#207840",
          "#000000",
          "#50a058",
          "#404040",
          "#709830",
          "#a0d038",
          "#e8e8f8",
          "#681018",
          "#d8d8f8",
          "#b83018"
        ],
        "idle": [
          {
            "ms": 300,
            "rows": [
              "....................",
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              ".efcgfeeeeefgce.....",
              ".efcgggggfgggcfe....",
              "..aegggffggggefe....",
              "..cfgggffggggfce....",
              "..cfhifgggfihfc.....",
              "..cfjkgggggkjfc.....",
              "..acffgggggffce.....",
              "..afccffgffccfc.....",
              "..cffacccccacc......",
              "...cc..............."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".......aaa..........",
              "......ababa.........",
              "....ccbdbbbcc.......",
              "...cbddddbbdbc......",
              "..cbbbdddbddbbc.....",
              "..cbeabbbbbaebc.....",
              "..ecgfeeeeefgcfe....",
              ".efcgggggfgggcfe....",
              ".efegggffggggea.....",
              ".ecfgggffggggfc.....",
              "..cfhifgggfihfc.....",
              "..cfjkgggggkjfc.....",
              "..ecffgggggffca.....",
              "..cfccffgffccfa.....",
              "...ccacccccaffc.....",
              "............cc......",
              "...................."
            ]
          }
        ],
        "walk": [
          {
            "ms": 300,
            "rows": [
              "....................",
              ".....aaaa...........",
              "..ccadddba.aaa......",
              ".cbbdddbbbccfgaa....",
              ".cbbbbbbecfgggffa...",
              ".abddbbeggggggffga..",
              "abbddbbefgggggggga..",
              "abbbbbbeffggggggfga.",
              "abbbbbbcfggggggggga.",
              ".abbbbcggfggghiggga.",
              "..ccccgggagggjkfgfa.",
              "...cfgggggagggggac..",
              "..cafffggffaaccc....",
              "..cacffafffcfa......",
              "...ccffccffca.......",
              ".....cc..cc.........",
              "...................."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".....aaaa...........",
              "..ccadddba.aaa......",
              ".cbbdddbbbccfgaa....",
              ".cbbbbbbecfgggffa...",
              ".abddbbeggggggffga..",
              "abbddbbefgggggggga..",
              "abbbbbbeffggggggfga.",
              "abbbbbbcfggggggggga.",
              ".abbbbcggfggghiggga.",
              "..ccccgggagggjkfgfa.",
              "...cfgggggagggggac..",
              "...cffgggffaaccc....",
              "..cffffccfffaa......",
              "..cffccaaacffc......",
              "...cc......cc.......",
              "....................",
              "...................."
            ]
          }
        ]
      }
    }
  },
  "charmander": {
    "width": 19,
    "height": 17,
    "variants": {
      "default": {
        "palette": [
          "#604020",
          "#f88838",
          "#b85820",
          "#e8e8f8",
          "#284858",
          "#000000",
          "#d8a830",
          "#f0d070",
          "#e02828"
        ],
        "idle": [
          {
            "ms": 300,
            "rows": [
              "...................",
              ".....aaaaa.........",
              "....abbbbba........",
              "...acbbbbbca.......",
              "...abbbbbbba.......",
              "...abcbbbcba.......",
              "..acdbbbbbdca......",
              "..acebbbbbeca......",
              "..fcebbbbbecf......",
              "...fccbbbccf.......",
              "...afcccccfa.......",
              "...fcfffffcf.......",
              "...fcaghgacf.......",
              "..acffhhhffca......",
              "..accghhhgcca......",
              "..accfaaafff.......",
              "...ff.............."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".....aaaaa.........",
              "....abbbbba........",
              "...acbbbbbca.......",
              "...abbbbbbba.......",
              "...abcbbbcba.......",
              "..acdbbbbbdca......",
              "..acebbbbbeca......",
              "..fcebbbbbecf......",
              "...fccbbbccf.......",
              "...afcccccfa.......",
              "...fcfffffcf.......",
              "...fcaghgacf.......",
              "..acffhhhffca......",
              "..accghhhgcca......",
              "...fffaaafcca......",
              "..........ff.......",
              "..................."
            ]
          }
        ],
        "walk": [
          {
            "ms": 300,
            "rows": [
              "...................",
              "...........aaaa....",
              ".i........abbbba...",
              ".ii......abbbbbba..",
              ".hi......abbbbbbc..",
              "iiii....abbbbbbcba.",
              "ihhi....abbbbbdcba.",
              ".ihi....abbbbbebbba",
              ".ii....abbbbbbebbbf",
              ".fca...abbbcabbbcf.",
              ".fccaaabbbcbcaffa..",
              "..fccbbbbcabbca....",
              "..fccccbbbcffff....",
              "...ffcccbbccga.....",
              ".....ffacccca......",
              ".......fccaa.......",
              "........fff........"
            ]
          },
          {
            "ms": 300,
            "rows": [
              "...........aaaa....",
              "...i......abbbba...",
              "...i.....abbbbbba..",
              "..ii.....abbbbbbc..",
              "..iii...abbbbbbcba.",
              ".iihi...abbbbbdcba.",
              ".ihhi...abbbbbebbba",
              ".ahi...abbbbbbebbbf",
              ".fca...abbbcabbbcf.",
              ".fccaaabbbcbcaffa..",
              "..fccbbbbbabbca....",
              "..fccccbbbbffff....",
              "...ffccccbbcga.....",
              ".....ffaacccca.....",
              "........afcca......",
              "..........fff......",
              "..................."
            ]
          }
        ]
      },
      "shiny": {
        "palette": [
          "#604020",
          "#f8c038",
          "#f88838",
          "#e8e8f8",
          "#284858",
          "#000000",
          "#d8a830",
          "#f0d070",
          "#e02828"
        ],
        "idle": [
          {
            "ms": 300,
            "rows": [
              "...................",
              ".....aaaaa.........",
              "....abbbbba........",
              "...acbbbbbca.......",
              "...abbbbbbba.......",
              "...abcbbbcba.......",
              "..acdbbbbbdca......",
              "..acebbbbbeca......",
              "..fcebbbbbecf......",
              "...fccbbbccf.......",
              "...afcccccfa.......",
              "...fcfffffcf.......",
              "...fcaghgacf.......",
              "..acffhhhffca......",
              "..accghhhgcca......",
              "..accfaaafff.......",
              "...ff.............."
            ]
          },
          {
            "ms": 300,
            "rows": [
              ".....aaaaa.........",
              "....abbbbba........",
              "...acbbbbbca.......",
              "...abbbbbbba.......",
              "...abcbbbcba.......",
              "..acdbbbbbdca......",
              "..acebbbbbeca......",
              "..fcebbbbbecf......",
              "...fccbbbccf.......",
              "...afcccccfa.......",
              "...fcfffffcf.......",
              "...fcaghgacf.......",
              "..acffhhhffca......",
              "..accghhhgcca......",
              "...fffaaafcca......",
              "..........ff.......",
              "..................."
            ]
          }
        ],
        "walk": [
          {
            "ms": 300,
            "rows": [
              "...................",
              "...........aaaa....",
              ".i........abbbba...",
              ".ii......abbbbbba..",
              ".hi......abbbbbbc..",
              "iiii....abbbbbbcba.",
              "ihhi....abbbbbdcba.",
              ".ihi....abbbbbebbba",
              ".ii....abbbbbbebbbf",
              ".fca...abbbcabbbcf.",
              ".fccaaabbbcbcaffa..",
              "..fccbbbbcabbca....",
              "..fccccbbbcffff....",
              "...ffcccbbccga.....",
              ".....ffacccca......",
              ".......fccaa.......",
              "........fff........"
            ]
          },
          {
            "ms": 300,
            "rows": [
              "...........aaaa....",
              "...i......abbbba...",
              "...i.....abbbbbba..",
              "..ii.....abbbbbbc..",
              "..iii...abbbbbbcba.",
              ".iihi...abbbbbdcba.",
              ".ihhi...abbbbbebbba",
              ".ahi...abbbbbbebbbf",
              ".fca...abbbcabbbcf.",
              ".fccaaabbbcbcaffa..",
              "..fccbbbbbabbca....",
              "..fccccbbbbffff....",
              "...ffccccbbcga.....",
              ".....ffaacccca.....",
              "........afcca......",
              "..........fff......",
              "..................."
            ]
          }
        ]
      }
    }
  }
}
