---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 4"

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - name: checkout the codebase
        uses: actions/checkout@v2

      - name: run make
        run: |
          make
